server:
  port: 1808

spring:
  application:
    name: aCloudMap
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/galigeigei?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=30000&autoReconnectForPools=true
#    url: jdbc:mysql://192.168.5.13:3306/galigeigei?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=30000&autoReconnectForPools=true
    username: galigeigei
    password: cp5BaBdhGCjLLfit
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql

parameters:
#  今日A股所有涨跌幅信息
  allInfo: https://82.push2.eastmoney.com/api/qt/clist/get

