//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "a_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub bk_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bk_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ej_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ej_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exchange: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
