//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::a_data_json::Entity as ADataJson;
pub use super::a_holiday::Entity as AHoliday;
pub use super::a_info::Entity as AInfo;
pub use super::a_sw::Entity as ASw;
pub use super::a_sw_dict::Entity as ASwDict;
pub use super::a_today::Entity as AToday;
